create database cinema;
use cinema;

create table salas(
idsala int auto_increment primary key,
num_sala varchar(10) not null,
capacidade int(3) not null,
horario varchar(5) not null,
preco int(3) not null, 
disponivel int(3) not null,
vendas int(3) not null
);
 
 create table filmes(
 idfilme int auto_increment primary key,
 titulo varchar(30) not null,
 duracao varchar(6) not null,
 sinopse varchar(1000) not null,
 /*vendas int(3) not null,*/
 id_sala int,
 foreign key (id_sala) references salas(idsala) 
 );
 
 INSERT INTO salas VALUES(default, "Sala1", 100, "15:00", 30, 100, 0),
 (default, "Sala1", 100, "18:00", 30, 100, 0),
  (default, "Sala2", 120, "17:00", 30, 120, 0),
   (default, "Sala3", 110, "22:00", 30, 110, 0),
    (default, "Sala4", 90, "16:00", 30, 90, 0),
     (default, "Sala4", 90, "20:00", 30, 90, 0),
      (default, "Sala5", 100, "18:00", 30, 100, 0),
       (default, "Sala6", 90, "21:00", 30, 90, 0),
        (default, "Sala7", 150, "15:00", 30, 150, 0),
         (default, "Sala7", 150, "20:30", 30, 150, 0);
 
 INSERT INTO filmes VALUES
 (default, "Órfã: A origem", "98min", "Em Órfã 2: A Origem, Leena Klammer/Esther Albright (Isabelle Fuhrman) está de volta para nos mostrar sua mente perversa e instável. Nesta prequela ao filme original de 2009, depois de orquestrar uma brilhante fuga de uma clínica psiquiátrica da Estônia, Esther viaja para os Estados Unidos se passando pela filha desaparecida de uma família rica que procura uma menina por quatro anos. Após ser acolhida pela nova família, luxo e uma psicóloga, 'Esther' começa a mostrar suas reais intenções com o pai e a mãe 'biológicos'. Esther começa a ser vigiada por um detetive, que fará tudo para mostrar à família que a menina não diz ser quem é de verdade, colocando em risco a nova identidade da órfã. No entanto, surge uma reviravolta inesperada que a coloca contra uma mãe que protegerá sua família da 'criança' assassina a qualquer custo, mesmo que signifique sua própria morte e a de todos.", 1),
  (default, "Órfã: A origem", "98min", "Em Órfã 2: A Origem, Leena Klammer/Esther Albright (Isabelle Fuhrman) está de volta para nos mostrar sua mente perversa e instável. Nesta prequela ao filme original de 2009, depois de orquestrar uma brilhante fuga de uma clínica psiquiátrica da Estônia, Esther viaja para os Estados Unidos se passando pela filha desaparecida de uma família rica que procura uma menina por quatro anos. Após ser acolhida pela nova família, luxo e uma psicóloga, 'Esther' começa a mostrar suas reais intenções com o pai e a mãe 'biológicos'. Esther começa a ser vigiada por um detetive, que fará tudo para mostrar à família que a menina não diz ser quem é de verdade, colocando em risco a nova identidade da órfã. No entanto, surge uma reviravolta inesperada que a coloca contra uma mãe que protegerá sua família da 'criança' assassina a qualquer custo, mesmo que signifique sua própria morte e a de todos.", 2),
  (default, "Não se preocupe, querida", "123min", "Em Não Se Preocupe, Querida, uma mulher (Florence Pugh) vive tranquilamente com o seu marido (Harry Styles) e os sócios dele, também acompanhados de suas esposas em um condomínio, em pleno anos 1950. As esposas vivem reclusas no local, onde esperam seus maridos chegarem do trabalho. Seu dia-a-dia consiste em dança, cozinhar, limpar a casa e festas noturnas com todos que moram no local. Seus maridos trabalham no Projeto Vitória, uma cidade utópica, com o objetivo de mudar o mundo. Em meio a tudo, uma delas começa a questionar o projeto e seu objetivo, que não é falado para as esposas pelos maridos. Ao começar a questionar seu entorno, a vida perfeita de esposa e marido começam a cair em ruínas à medida que os segredos da empresa do Projeto Vitória vem à tona e mulheres acabam se suicidando ou desaparecendo. Neste thriller psicológico, a vida perfeita se mistura com ficção e sair da cidade não vai ser uma tarefa fácil. ", 3),
  (default, "O telefone preto", "103min", "Em O Telefone Preto, em 1978, uma série de sequestros estão acontecendo na cidade de Denver. Ethan Hawke interpreta o 'Grabbler', um serial killer que tem seu alvo crianças do bairro. Finney Shaw, um garoto de 13 anos, é sequestrado. o garoto acorda em um porão, onde há apenas uma cama e um telefone preto em uma das paredes. Quando o aparelho toca, o garoto consegue ouvir a voz das vítimas anteriores do assassino, e elas tentam evitar que o Finney sofra o mesmo destino. Enquanto isso, sua irmã Gwen tem sonhos que indicam o lugar onde ele pode estar e corre contra o tempo para tentar ajudar os detetives Wright e Miller a ajudar o irmão, apenas para que isso seja em vão. Finney continua a fazer tentativas para escapar que apenas falham, até que uma das vítimas do serial killler fala sobre um plano que finalmente poderia levar Finney à liberdade.", 4),
  (default, "A mulher rei", "120min", "A Mulher Rei acompanha Nanisca (Viola Davis) que foi uma comandante do exército do Reino de Daomé, um dos locais mais poderosos da África nos séculos XVII e XIX. Durante o período, o grupo militar era composto apenas por mulheres que, juntas, combateram os colonizadores franceses, tribos rivais e todos aqueles que tentaram escravizar seu povo e destruir suas terras. Conhecidas como Agojie, o grupo foi criado por conta de sua população masculina enfrentar altas baixas na violência e guerra cada vez mais frequentes com os estados vizinhos da África Ocidental, o que levou Dahomey a ser forçado a dar anualmente escravos do sexo masculino, particularmente ao Império Oyo, que usou isso para troca de mercadorias como parte do crescente fenômeno do comércio de escravos na África Ocidental durante a Era dos Descobrimentos, o que fez com que mulheres fossem alistadas para o combate.", 5),
    (default, "A mulher rei", "120min", "A Mulher Rei acompanha Nanisca (Viola Davis) que foi uma comandante do exército do Reino de Daomé, um dos locais mais poderosos da África nos séculos XVII e XIX. Durante o período, o grupo militar era composto apenas por mulheres que, juntas, combateram os colonizadores franceses, tribos rivais e todos aqueles que tentaram escravizar seu povo e destruir suas terras. Conhecidas como Agojie, o grupo foi criado por conta de sua população masculina enfrentar altas baixas na violência e guerra cada vez mais frequentes com os estados vizinhos da África Ocidental, o que levou Dahomey a ser forçado a dar anualmente escravos do sexo masculino, particularmente ao Império Oyo, que usou isso para troca de mercadorias como parte do crescente fenômeno do comércio de escravos na África Ocidental durante a Era dos Descobrimentos, o que fez com que mulheres fossem alistadas para o combate.", 6),
      (default, "Avatar", "150min", "Jake Sully (Sam Worthington) ficou paraplégico após um combate na Terra. Ele é selecionado para participar do programa Avatar em substituição ao seu irmão gêmeo, falecido. Jake viaja a Pandora, uma lua extraterrestre, onde encontra diversas e estranhas formas de vida. O local é também o lar dos Na'Vi, seres humanóides que, apesar de primitivos, possuem maior capacidade física que os humanos. Os Na'Vi têm três metros de altura, pele azulada e vivem em paz com a natureza de Pandora. Os humanos desejam explorar a lua, de forma a encontrar metais valiosos, o que faz com que os Na'Vi aperfeiçoem suas habilidades guerreiras. Como são incapazes de respirar o ar de Pandora, os humanos criam seres híbridos chamados de Avatar. Eles são controlados por seres humanos, através de uma tecnologia que permite que seus pensamentos sejam aplicados no corpo do Avatar. Desta forma Jake pode novamente voltar à ativa, com seu Avatar percorrendo as florestas de Pandora e liderando soldados. Até conhecer Neytiri (Zoe Saldana), uma feroz Na'Vi que conhece acidentalmente e que serve de tutora para sua ambientação na civilização alienígena.", 7),
        (default, "Sorria", "115min", "Em Sorria, tudo na vida da Dra. Rose Cotter (Sosie Bacon) muda, após uma paciente morrer de forma brutal em sua frente, e ela testemunhar o incidente bizarro e traumático no consultório. A partir daí, ela começa a experimentar ocorrências assustadoras que ela não consegue explicar, mas que de alguma forma, se relacionam com a morte que ela presenciou. Para entender o fenômeno que não sai de sua cabeça, a Dra. irá atrás de respostas, mesmo que o mal também já esteja perseguindo-a, e tudo que ela mais quer, é também fugir. Rose irá até as últimas consequências, com o objetivo de desvendar e combater o mal desconhecido que começou a afetar sua vida e de todos ao seu redor. Cada dia mais imersa nessa teia de acontecimentos assustadores, para sobreviver, ela deverá enfrentar a situação perturbadora que se apresenta, e tentar escapar de sua nova e horrível realidade.", 8),
          (default, "A queda", "107min", "Para as melhores amigas Becky (Grace Caroline Currey) e Hunter (Virginia Gardner), a vida é sobre vencer medos e ultrapassar limites. A alpinista emocionalmente abalada, Becky, afogada em um mar de tristeza, vivendo semanas dolorosas após o incidente que a marcou para toda a vida, relutantemente decide enfrentar seus fantasmas quando sua amiga, outra alpinista experiente, a convence a embarcar em uma aventura de escalada de alto risco, até o topo de uma torre de TV abandonada. No entanto, depois de subir até o topo da torre de rádio remota e abandonada, elas se encontram sem saída. Quando a escalada perigosa não sai como planejado, as mulheres devem reunir toda a coragem e força para elaborar um plano para um retorno seguro para casa - ou morrer tentando. Agora, as habilidades de escalada de Becky e Hunter serão postas à prova enquanto lutam desesperadamente para sobreviver aos elementos, à falta de suprimentos e à altura extrema.", 9),
            (default, "A queda", "107min", "Para as melhores amigas Becky (Grace Caroline Currey) e Hunter (Virginia Gardner), a vida é sobre vencer medos e ultrapassar limites. A alpinista emocionalmente abalada, Becky, afogada em um mar de tristeza, vivendo semanas dolorosas após o incidente que a marcou para toda a vida, relutantemente decide enfrentar seus fantasmas quando sua amiga, outra alpinista experiente, a convence a embarcar em uma aventura de escalada de alto risco, até o topo de uma torre de TV abandonada. No entanto, depois de subir até o topo da torre de rádio remota e abandonada, elas se encontram sem saída. Quando a escalada perigosa não sai como planejado, as mulheres devem reunir toda a coragem e força para elaborar um plano para um retorno seguro para casa - ou morrer tentando. Agora, as habilidades de escalada de Becky e Hunter serão postas à prova enquanto lutam desesperadamente para sobreviver aos elementos, à falta de suprimentos e à altura extrema.", 10);